kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: event-reader
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "patch", "watch", "list", "create"]
